default_context:
  project_name: 'websitetestsframework'
  project_slug: 'websitetestsframework'
  domain_main: 'websitetestsframework.com'
  domain_staging: 'stag.websitetestsframework.com'
  domain_base_api_url: 'http://websitetestsframework.com/api/v1'
  domain_base_ws_url: 'ws://websitetestsframework.com/api/v1'
  docker_swarm_stack_name_main: 'websitetestsframework-com'
  docker_swarm_stack_name_staging: 'stag-websitetestsframework-com'
  secret_key: 'nicopw!'
  first_superuser: 'admin@websitetestsframework.com'
  first_superuser_password: 'nicolopw!'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.websitetestsframework.com", "https://stag.websitetestsframework.com", "https://websitetestsframework.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@websitetestsframework.com'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@websitetestsframework.com'
  postgres_password: 'nicopw!'
  pgadmin_default_user: 'admin@websitetestsframework.com'
  pgadmin_default_user_password: 'nicopw!'
  neo4j_password: 'nicopw!'
  traefik_constraint_tag: 'websitetestsframework.com'
  traefik_constraint_tag_staging: 'stag.websitetestsframework.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:nicopw!'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
