"""schedule update with time object

Revision ID: 416ebf55fd13
Revises: f4554df668dd
Create Date: 2023-08-14 09:49:00.429869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416ebf55fd13'
down_revision = 'f4554df668dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduleinfo', sa.Column('time', sa.Time(timezone=True), server_default='00:00:00+00:00', nullable=False))
    op.drop_column('scheduleinfo', 'min')
    op.drop_column('scheduleinfo', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduleinfo', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scheduleinfo', sa.Column('min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('scheduleinfo', 'time')
    # ### end Alembic commands ###
