"""Add column to crontab entity

Revision ID: b7acf845ed4d
Revises: 3ae0605c3d40
Create Date: 2023-08-03 14:04:02.043982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7acf845ed4d'
down_revision = '3ae0605c3d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crontab', sa.Column('last_time_launched', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crontab', 'last_time_launched')
    # ### end Alembic commands ###
