"""Schedule info days as array

Revision ID: f4554df668dd
Revises: 33b5c8793e46
Create Date: 2023-08-11 12:16:50.460651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4554df668dd'
down_revision = '33b5c8793e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduleinfo_day_id', table_name='scheduleinfo_day')
    op.drop_table('scheduleinfo_day')
    op.drop_index('ix_scheduleday_id', table_name='scheduleday')
    op.drop_table('scheduleday')
    op.add_column('scheduleinfo', sa.Column('days', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduleinfo', 'days')
    op.create_table('scheduleinfo_day',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheduleinfo_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scheduleday_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scheduleday_id'], ['scheduleday.id'], name='scheduleinfo_day_scheduleday_id_fkey'),
    sa.ForeignKeyConstraint(['scheduleinfo_id'], ['scheduleinfo.id'], name='scheduleinfo_day_scheduleinfo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduleinfo_day_pkey')
    )
    op.create_index('ix_scheduleinfo_day_id', 'scheduleinfo_day', ['id'], unique=False)
    op.create_table('scheduleday',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='scheduleday_pkey')
    )
    op.create_index('ix_scheduleday_id', 'scheduleday', ['id'], unique=False)
    # ### end Alembic commands ###
