name: publish
on: 
    push:
        paths:
            - './backend/**'
            - './frontend/**'
jobs:
    publish-docker-images:
        runs-on: ubuntu-latest
        steps:
        - 
            uses: actions/checkout@v2
        - 
            name: Login to Github Container Registry
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        - 
            name: Build backend image
            run: |
                docker build -f ./backend/backend.dockerfile ./backend --tag ghcr.io/nicobboi/website-tests-backend:latest
                docker push ghcr.io/nicobboi/website-tests-backend:latest
        - 
            name: Build celery image
            run: |
                docker build -f ./backend/celeryworker.dockerfile ./backend --tag ghcr.io/nicobboi/website-tests-celeryworker:latest
                docker push ghcr.io/nicobboi/website-tests-celeryworker:latest
        - 
            name: Build frontend image
            run: |
                docker build -f ./frontend/frontend.dockerfile ./frontend --tag ghcr.io/nicobboi/website-tests-frontend:latest
                docker push ghcr.io/nicobboi/website-tests-frontend:latest
            