name: publish
on: 
    workflow_run:
        workflows: [test images]
        types: [completed]

permissions: write-all
jobs:
    publish-docker-images:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - 
            uses: actions/checkout@v2
        - 
            name: Login to Github Container Registry
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        - 
            name: Build and push to registry backend image
            run: |
                docker build -f ./backend/backend.dockerfile ./backend --tag ghcr.io/nicobboi/website-tests-backend:latest
                docker push ghcr.io/nicobboi/website-tests-backend:latest
        - 
            name: Build and push to registry celery image
            run: |
                docker build -f ./backend/celeryworker.dockerfile ./backend --tag ghcr.io/nicobboi/website-tests-celeryworker:latest
                docker push ghcr.io/nicobboi/website-tests-celeryworker:latest
        - 
            name: Build and push to registry frontend image
            run: |
                docker build -f ./frontend/frontend.dockerfile ./frontend --tag ghcr.io/nicobboi/website-tests-frontend:latest
                docker push ghcr.io/nicobboi/website-tests-frontend:latest
            
